// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/voterinfo": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/voterinfo";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/voterinfo.tsx": {
    id: "routes/voterinfo";
    page: "/voterinfo";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/voterinfo": typeof import("./app/routes/voterinfo.tsx");
};